// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3JqKIZft-G5xD538z_GheWAkw3b5EEMU',
    appId: '1:729232095040:web:e4fc7aeb1d114ee26b6ca5',
    messagingSenderId: '729232095040',
    projectId: 'almacenlospilas-bfc9f',
    authDomain: 'almacenlospilas-bfc9f.firebaseapp.com',
    storageBucket: 'almacenlospilas-bfc9f.appspot.com',
    measurementId: 'G-YGYT39GS0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7_8nRDdzFpX_XQqhjpO_OanMtfATQWrY',
    appId: '1:729232095040:android:a43dc9ac011a77076b6ca5',
    messagingSenderId: '729232095040',
    projectId: 'almacenlospilas-bfc9f',
    storageBucket: 'almacenlospilas-bfc9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlhsfjhyliQNBKxRu8BKXYjMZgwsIDM68',
    appId: '1:729232095040:ios:b9709b591fd4e3956b6ca5',
    messagingSenderId: '729232095040',
    projectId: 'almacenlospilas-bfc9f',
    storageBucket: 'almacenlospilas-bfc9f.appspot.com',
    iosBundleId: 'com.example.almacenLosPilas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlhsfjhyliQNBKxRu8BKXYjMZgwsIDM68',
    appId: '1:729232095040:ios:b9709b591fd4e3956b6ca5',
    messagingSenderId: '729232095040',
    projectId: 'almacenlospilas-bfc9f',
    storageBucket: 'almacenlospilas-bfc9f.appspot.com',
    iosBundleId: 'com.example.almacenLosPilas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3JqKIZft-G5xD538z_GheWAkw3b5EEMU',
    appId: '1:729232095040:web:1634d56815a224df6b6ca5',
    messagingSenderId: '729232095040',
    projectId: 'almacenlospilas-bfc9f',
    authDomain: 'almacenlospilas-bfc9f.firebaseapp.com',
    storageBucket: 'almacenlospilas-bfc9f.appspot.com',
    measurementId: 'G-WDYT86G8BG',
  );
}
